# To use this compose file, first build the container(s).
# docker build -t library/postgres:latest -f Dockerfile.pgjwt .
version: "3"
services:
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    networks:
      - postgrest
    environment:
      PGRST_DB_URI: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      PGRST_DB_SCHEMAS: api
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_JWT_SECRET: "${PGRST_JWT_SECRET}"
    depends_on:
      - db
  db:
    image: library/postgres
    ports:
      - "5432:5432"
    networks:
      - postgrest
    command: postgres -c app.jwt_secret='${PGRST_JWT_SECRET}'
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - "./data/database:/var/lib/postgresql/data"
      - "./init:/docker-entrypoint-initdb.d"
networks:
  postgrest: